<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\JobOffer;

class JobOffersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jobOffers = [
            // وظائف للشركة الأولى (10 وظائف)
            ['title' => 'Web Developer', 'description' => 'A web developer is needed to work on front-end and back-end development using technologies like PHP, Laravel, JavaScript, and MySQL. The candidate should have a strong understanding of HTML, CSS, and responsive design.', 'work_hours' => 40, 'salary' => 900, 'location' => 'Amman', 'requirements' => 'Experience with Laravel and JavaScript frameworks is required. A portfolio of previous web development projects will be preferred.', 'deadline' => '2025-06-30', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'Software Engineer', 'description' => 'We are looking for a passionate software engineer with strong problem-solving skills and experience in backend development, working with Java, Python, or C++.', 'work_hours' => 40, 'salary' => 950, 'location' => 'Amman', 'requirements' => 'Minimum 2 years of experience in software engineering with Java or Python. Understanding of algorithms and data structures is a must.', 'deadline' => '2025-07-15', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'Mobile App Developer', 'description' => 'Develop mobile applications for both iOS and Android platforms. Experience with React Native or Flutter is a plus. The candidate should have strong problem-solving and debugging skills.', 'work_hours' => 35, 'salary' => 850, 'location' => 'Amman', 'requirements' => 'Experience in mobile app development, particularly with cross-platform technologies like React Native or Flutter. Portfolio required.', 'deadline' => '2025-05-20', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'IT Support Specialist', 'description' => 'We are seeking an IT Support Specialist who will provide technical support to internal teams, troubleshoot hardware and software issues, and maintain the company’s IT infrastructure.', 'work_hours' => 40, 'salary' => 700, 'location' => 'Irbid', 'requirements' => 'Strong knowledge of network and server management, with experience in providing IT support in an office environment.', 'deadline' => '2025-06-05', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'UX/UI Designer', 'description' => 'Looking for a creative UX/UI Designer to design user-friendly interfaces and ensure a seamless user experience across web and mobile platforms. Proficiency in design tools like Adobe XD and Figma is required.', 'work_hours' => 40, 'salary' => 800, 'location' => 'Amman', 'requirements' => 'Experience with UX/UI design principles. Portfolio with previous design work is mandatory.', 'deadline' => '2025-08-01', 'is_active' => true, 'category' => 'Design', 'company_id' => 1],
            ['title' => 'Frontend Developer', 'description' => 'We need a frontend developer who is proficient in HTML, CSS, JavaScript, and React. The candidate should have a strong understanding of web design principles and the ability to build responsive websites.', 'work_hours' => 40, 'salary' => 850, 'location' => 'Amman', 'requirements' => 'Proven experience in front-end development with React. Strong knowledge of JavaScript and CSS frameworks.', 'deadline' => '2025-07-12', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'Data Scientist', 'description' => 'We are hiring a Data Scientist to work on analyzing complex datasets, building predictive models, and using machine learning to drive business insights. Strong programming skills are required in Python or R.', 'work_hours' => 40, 'salary' => 1000, 'location' => 'Amman', 'requirements' => 'At least 2 years of experience in data science or related fields. Experience with data visualization tools like Tableau or PowerBI is a plus.', 'deadline' => '2025-07-30', 'is_active' => true, 'category' => 'IT', 'company_id' => 1],
            ['title' => 'Product Manager', 'description' => 'We need a Product Manager who will be responsible for the development and management of our product roadmap, and work closely with engineering and design teams to launch successful products.', 'work_hours' => 40, 'salary' => 1100, 'location' => 'Amman', 'requirements' => 'Experience in product management or project management. Strong communication skills are required.', 'deadline' => '2025-06-10', 'is_active' => true, 'category' => 'Design', 'company_id' => 1],
            ['title' => 'SEO Specialist', 'description' => 'We are looking for an SEO Specialist to optimize website content and improve search engine rankings using the latest SEO strategies. A solid understanding of Google Analytics and SEO tools is a must.', 'work_hours' => 35, 'salary' => 750, 'location' => 'Amman', 'requirements' => 'At least 1 year of experience in SEO and online marketing. Familiarity with tools such as Google Analytics, SEMrush, or Ahrefs.', 'deadline' => '2025-05-15', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 1],

            // وظائف للشركة الثانية (11 وظائف)
            ['title' => 'Graphic Designer', 'description' => 'Looking for a talented Graphic Designer to create visually appealing designs for print and digital media. Experience with Adobe Creative Suite required.', 'work_hours' => 40, 'salary' => 800, 'location' => 'Amman', 'requirements' => 'Experience with Adobe Photoshop, Illustrator, and InDesign. Portfolio of previous designs required.', 'deadline' => '2025-07-20', 'is_active' => true, 'category' => 'Design', 'company_id' => 2],
            ['title' => 'Content Writer', 'description' => 'A creative and detail-oriented Content Writer is needed to write blogs, articles, and marketing materials for various platforms.', 'work_hours' => 35, 'salary' => 650, 'location' => 'Amman', 'requirements' => 'Strong writing skills and the ability to create engaging content. Experience in writing for digital marketing is a plus.', 'deadline' => '2025-06-25', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'Social Media Manager', 'description' => 'We are hiring a Social Media Manager to handle our online presence across multiple social media platforms. The ideal candidate should have experience with social media analytics and content creation.', 'work_hours' => 38, 'salary' => 700, 'location' => 'Amman', 'requirements' => 'Proven track record of social media growth. Familiarity with Facebook Ads and Instagram is a must.', 'deadline' => '2025-08-05', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'Accountant', 'description' => 'A skilled Accountant is needed to manage financial records, prepare reports, and ensure tax compliance. Experience with accounting software like QuickBooks or Xero is preferred.', 'work_hours' => 40, 'salary' => 750, 'location' => 'Amman', 'requirements' => 'At least 2 years of accounting experience. Strong knowledge of financial reporting and tax laws.', 'deadline' => '2025-06-15', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'Sales Manager', 'description' => 'We are looking for an experienced Sales Manager to lead our sales team, set targets, and create sales strategies to achieve business goals.', 'work_hours' => 40, 'salary' => 950, 'location' => 'Amman', 'requirements' => 'At least 3 years of experience in sales management. Strong leadership and negotiation skills.', 'deadline' => '2025-07-01', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'HR Specialist', 'description' => 'An HR Specialist is needed to manage recruitment, employee relations, and performance management within the company. Excellent communication skills are required.', 'work_hours' => 40, 'salary' => 850, 'location' => 'Amman', 'requirements' => 'Experience in HR management. Knowledge of labor laws and hiring processes.', 'deadline' => '2025-06-30', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'Project Manager', 'description' => 'Looking for a Project Manager to oversee various projects, ensuring they are completed on time and within budget. Strong leadership and organizational skills are essential.', 'work_hours' => 40, 'salary' => 1100, 'location' => 'Amman', 'requirements' => 'At least 2 years of project management experience. Strong knowledge of project management tools.', 'deadline' => '2025-07-10', 'is_active' => true, 'category' => 'Design', 'company_id' => 2],
            ['title' => 'Marketing Coordinator', 'description' => 'We need a Marketing Coordinator to assist with the execution of marketing strategies, manage events, and help with campaigns. Experience in event planning is a plus.', 'work_hours' => 40, 'salary' => 700, 'location' => 'Amman', 'requirements' => 'Experience in marketing and event coordination. Strong communication and organizational skills.', 'deadline' => '2025-06-20', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
            ['title' => 'Customer Support Specialist', 'description' => 'Hiring a Customer Support Specialist to provide assistance and resolve issues for our clients. Excellent communication skills and problem-solving ability are required.', 'work_hours' => 40, 'salary' => 600, 'location' => 'Amman', 'requirements' => 'Experience in customer support. Strong phone and email communication skills.', 'deadline' => '2025-08-01', 'is_active' => true, 'category' => 'Design', 'company_id' => 2],
            ['title' => 'Business Development Manager', 'description' => 'We are looking for a Business Development Manager to identify new business opportunities, negotiate contracts, and build strong relationships with clients.', 'work_hours' => 40, 'salary' => 1200, 'location' => 'Amman', 'requirements' => 'At least 3 years of experience in business development. Strong negotiation and communication skills.', 'deadline' => '2025-07-25', 'is_active' => true, 'category' => 'Marketing', 'company_id' => 2],
        ];

        foreach ($jobOffers as $jobOffer) {
            JobOffer::create($jobOffer);
        }
    }
}
